MraZ = {
  "protein": "MraZ",
  "gene": ["mraZ", "yabB"],
  "EC": ["-"],
  "alt": ["MraZ", "YabB", 
          "transcriptional regulator MraZ"],
  "OrthoDB": "-",
  "eggNOG": "COG2001",
  "Pfam": ["PF02381"],
  "UniProt": "O07103",
  "protein_id": "WP_002355890.1",
  "ref_organism": "Enterococcus faecalis",
  "organism_detail": "strain ATCC 700802/V583",
  "accession": "AAO80794",
  "ref_seq": "MLMGEYQHNIDAKGRLIVPSKFREELGEKFVVTRGMDGCLFGYPLNEWSQLEAKLQEMPLAKKDARTFVRFFYSAATECEIDKQGRINIPANLRTHASLEKGCVVIGVSNRIEIWSDERWHAFSDEAEENFDELAETMIDFGF",
  "article_based": True
}

MraW = {
  "protein": "MraW",
  "gene": ["mraW", "yabC", "rsmH"],
  "EC": ["2.1.1.199"],
  "alt": ["MraW", "YabC", "RsmH", 
          "rRNA small subunit methyltransferase H"],
  "OrthoDB": "-",
  "eggNOG": "-",
  "Pfam": ["PF01795"],
  "UniProt": "O07104",
  "protein_id": "WP_002355891.1",
  "ref_organism": "Enterococcus faecalis",
  "organism_detail": "strain ATCC 700802/V583",
  "accession": "AAO80795",
  "ref_seq": "MTEEFRHYTVLLKETVDGLQVKPDGVYVDCTLGGAGHSEYLLTQLNEHGHLYAFDQDQKALAHAKTRLQKYVDKGQVTFIKSNFRNIKEELAEHGVFHVDGILYDLGVSSPQLDEAERGFSYHQDAPLDMRMDQDAPLTAREVVNTYSYSELVKIFFRYGEEKFSKQIAREIERVREKQPIETTGELVEIIKTAIPAPARRKGGHPAKRIFQAIRIAVNDELGAVEESLEQAIDLLAKNGRISVITFHSLEDRIVKTMFKEYSTVQDLPPGIPVVPEEFQPELKVITRKPILPSDSELSENNRSRSAKLRIAEKIKSR",
  "article_based": True
}

FtsL = {
  "protein": "FtsL",
  "gene": ["ftsL", "mraR", "yabD"],
  "EC": ["-"],
  "alt": ["FtsL", "MraR", "YabD", 
          "cell division protein FtsL"],
  "OrthoDB": "-",
  "eggNOG": "-",
  "Pfam": ["PF19579"],
  "UniProt": "A0A1L8RD94",
  "protein_id": "WP_067395339.1",
  "ref_organism": "Enterococcus canis",
  "organism_detail": "-",
  "accession": "OJG17713",
  "ref_seq": "MAELKKFEEYQLDIPVIAEPAKDQPIEIEVTTTSPKKKLRHITYLERIVVMALVVAGVALAVMTIQMRTSVNQTLTDIGQIQNEVNTTKTDITRLEQEKGELSRADRVQKIAKEKGLKDHADNIRKVK",
  "article_based": False
}

FtsI = {
  "protein": "FtsI",
  "gene": ["ftsI", "pbpB"],
  "EC": ["3.4.16.4"],
  "alt": ["FtsI" "PbpB", "Pbp3", 
          "peptidoglycan D,D-transpeptidase FtsI", 
          "penicillin-binding protein 3",],
  "OrthoDB": "-",
  "eggNOG": "COG0768",
  "Pfam": ["PF03793", "PF03717", "PF00905"],
  "UniProt": "Q836V7",
    "protein_id": "WP_002381310.1",
  "ref_organism": "Enterococcus faecalis",
  "organism_detail": "strain ATCC 700802/V583",
  "accession": "AAC36836",
  "ref_seq": "MSKRHKFKQFMKKKNLNPMNNRKKVGIILFATSIGLFFLFAFRTTYIVATGKVAGVSLKEKTASLYEGSQVVKAKRGSILDRYGNPIAEDATSYSLYVVLSKKYTGQNNEKLYAEKKDFDDIAEILAKYTKLDKKTALKYLNNGIHEDGSTQYQVEFGTGGQNITLETRQKIEADLKKKKISGVYFNEHPARLYPNGQFASHFIGYTKAANPDDDKEGLVGAMGLEQTYNDILSGTDGRVYFEKDIYGNALPGTVAEEKKAVDGQDIYTTLDSRLQNTLEDLMTQVNEKYEPVSMTAMLMEAKTGEIVAMSQRPTFNPETKQGLDDNGTWQNLLVESPYEPGSTIKLFTTAASMEQGQFNPNELFNRVGGIQVGDVTVNDHDYTRLNGKEYLNYRQAISWSSNIGMVKLEQKMGDEKWMEYLKKFGFGTSTHSGLSGESAGKLPGTNFVDRAMSAFGQAITVTNFQMMKGFSAIANDGSMLQPHYISKIVDKNTGKETITEPQIVGTPIKAQTAQQIRTYMIDTVEDPTYGIAYDIYKVPGYHVAAKTGTAQISDGKGYVDGASQVLSSVVEMVPADNPEYVLYITLRQAKSGSPSEAMAAIANPLMKLALDIKETDPETTKVASDKVTVADYKNMTPAEALANAKVNGVDPVIIGDGEKIKKQSTPSGQTLMPNQKLILITNGTNYMPDLTGWSKSDVTKFGDLLGLTVEFKGEGYVTKQSIAAETEITEKKLTVTLEGTE",
  "article_based": True
}

MurE = {
  "protein": "MurE",
  "gene": ["murE"],
  "EC": ["6.3.2.7", "6.3.2.13"],
  "alt": ["MurE",
          "L-lysine-adding enzyme",
          "UDP-MurNAc-tripeptide synthetase",
          "UDP-N-acetylmuramyl-tripeptide synthetase",
          "UDP-N-acetylmuramoyl-L-alanyl-D-glutamate--2,6-diaminopimelate ligase", 
          "UDP-N-acetylmuramoyl-L-alanyl-D-glutamate--2, 6-diaminopimelate ligase", 
          "UDP-N-acetylmuramoylalanyl-D-glutamate 2,6-diaminopimelate ligase",
          "UDP-N-acetylmuramoylalanyl-D-glutamate 2, 6-diaminopimelate ligase"],
  "OrthoDB": "-",
  "eggNOG": "COG0769",
  "Pfam": ["PF02875", "PF08245"],
  "UniProt": "Q838A4",
  "protein_id": "WP_002371461.1",
  "ref_organism": "Enterococcus faecalis",
  "organism_detail": "strain ATCC 700802/V583",
  "accession": "AAO80491",
  "ref_seq": "MTISLFAIRDCLEKEDLLKEFISPEGWHLTLSDTLGQREVTALSYDSRDVTAETLFFCKGLNFKEIYLENAVKDGLEIYVSEVPYEVPAQLGIIVTDIKKAMAVLSMAFYDYPQNKLKLIGFTGTKGKTTAAYFTKYILDVATQQKTALLSTMNSTLDGKTFFKSALTTPESLDLYRMMATAVANGMTHFIMEVSSQAYKTNRVYKLFFDVGIFLNITPDHISPIEHPTFDDYFYCKRQLITHSKVIVLNHEADYFPLLKETAQQQKVPAIVYGSQPAPEVDYSFAVSSEDSLRFIVESPADALGLAGSYHLRLGGDFNKGNALSAAIASVLVGASKEECQQGIAATTVPGRMESLTNTNGATVYVDYAHNYDSLKNLLTFVREEHPDGRLIVLVGSTGDKAISRRKDFGRVLSELADVAVLTTDDPASEDPAKICQEIQAHITKEMPVYTVLDRGEAIAHALSLSTTADDAIVLAGKGADLYQKVNGVDEPYAGDFALAEAFINKKN",
  "article_based": True
}

MurF = {
  "protein": "MurF",
  "gene": ["murF"],
  "EC": ["6.3.2.10"],
  "alt": ["MurF",
          "UDP-N-acetylmuramoyl-tripeptide--D-alanyl-D-alanine ligase", 
          "UDP-N-acetylmuramoyl-pentapeptide"],
  "OrthoDB": "-",
  "eggNOG": "COG0770",
  "Pfam": ["PF02875", "PF08245"],
  "UniProt": "Q837J3",          
  "protein_id": "WP_002355722.1",
  "ref_organism": "Enterococcus faecalis",
  "organism_detail": "strain ATCC 700802/V583",
  "accession": "AAO80657",
  "ref_seq": "MKLTFWEVAQAVEASNDWQQWPDFPLTGIEFDSRKIVKGNLFVPLQGENDGHRFIESAMANGCQAAFWGQDLVDAPQQLPVLHVTDPLVAMQKLATYYLNKMQPNVIAVTGSNGKTTTKDLIAAVLSEKFVTYKTQGNYNNQIGLPYTILHMPDETEKLILEMGMDHAQEISFLSNLAQPEVAAITMIGEAHVENLGSRAGIAQAKMEIVDGLAKDGSLFVPSDEPLLEPLVEKVTQQVITFGFSQESQLQGIVTNEAKEQTSFKISDTQMTFTIPVPGTYNVTNALIAIGIGRYFQLTDSEIQKGLATAELTKNRTEWLKAANGAEILSDVYNANPTAMGLVLDSFSKMSKVGKRIAVLGDMLELGPDSAAMHQAMAQHLAPDAIEEVFLYGSEMAYLADKLQETYAPANIHSFKKEEKNELIEAVKKVLQPEDMVVLKGSNGMGLREVIDALLEK",
  "article_based": True,
}

MraY = {
  "protein": "MraY",
  "gene": ["mraY", "murX"],
  "EC": ["2.7.8.13"],
  "alt": ["MraY", "MurX", 
          "Phospho-N-acetylmuramoyl-pentapeptide-transferase",
          "UDP-MurNAc-pentapeptide phosphotransferase"],
  "OrthoDB": "-",
  "eggNOG": "COG0472",
  "Pfam": ["PF00953"], 
  "UniProt": "O07107",
  "protein_id": "WP_002355894.1",
  "ref_organism": "Enterococcus faecalis",
  "organism_detail": "strain ATCC 700802/V583",
  "accession": "AAO80798",
  "ref_seq": "MEWTQIFIPIVVSFAITVSVMPLFIGYFQMKKQGQVTREDGPTWHSVKTGTPTMGGVVFLVASLITSLAMGLFFHQFTPSLLIILFILVLYGLLGYLDDFIKVFKKRNMGLNSRQKLIGQIFGGLVFYFVYRSEGFSDTLDLFGVAEVPLGIFYGVFIIFWLVGFSNAVNLTDGIDGLVAGLGTISFGTYAIIAWKQQQFDVVIICLSVIGGLIGFFPYNRKPAKIFMGDVGSLALGGLLAAISIILHQEWTLLLIGLVYVCETASVILQVASFKLFGRRIFKMSPIHHHFEMCGWSEWKIDFVFWSVGLICSGITLWILF",
  "article_based": True
}

MurD = {
  "protein": "MurD",
  "gene": ["murD"],
  "EC": ["6.3.2.9"],
  "alt": ["MurD",
          "D-glutamic acid-adding enzyme",
          "UDP-N-acetylmuramoylalanine--D-glutamate ligase", 
          "UDP-N-acetylmuramoylalanine-D-glutamate ligase"],
  "OrthoDB": "-",
  "eggNOG": "COG0771",
  "Pfam": ["PF02875", "PF08245"],
  "UniProt": "O07108",   
  "protein_id": "WP_002379203.1",
  "ref_organism": "Enterococcus faecalis",
  "organism_detail": "strain ATCC 700802/V583",     
  "accession": "AAO80799",
  "ref_seq": "MKKITTYQNKKVLVLGLAKSGVSAAKLLHELGALVTVNDAKQFDQNPDAQDLLTLGIRVVTGGHPIELLDEEFELIVKNPGIPYTNPLVAEALTRKIPIITEVELAGQIAECPIVGITGTNGKTTTTTMIGLLLNADRTAGEARLAGNIGFPASTVAQEATAKDNLVMELSSFQLMGIETFHPQIAVITNIFEAHLDYHGSRKEYVAAKWAIQKNMTAEDTLILNWNQVELQTLAKTTAANVLPFSTKEAVEGAYLLDGKLYFNEEYIMPADELGIPGSHNIENALAAICVAKLKNVSNAQIRQTLTNFSGVPHRTQFVGEVQQRRFYNDSKATNILATEMALSGFDNQKLLLLAGGLDRGNSFDELVPALLGLKAIVLFGETKEKLAEAAKKANIETILFAENVQTAVTIAFDYSEKDDTILLSPACASWDQYPNFEVRGEAFMQAVQQLKESEM",
  "article_based": True
}

FtsW = {
  "protein": "FtsW",
  "gene": ["ftsW", "ylaO"],
  "EC": ["2.4.1.129"],
  "alt": ["FtsW", "YlaO", 
          "Probable peptidoglycan glycosyltransferase FtsW"],
  "OrthoDB": "-",
  "eggNOG": "COG0772",
  "Pfam": ["PF01098"],
  "UniProt": "Q820T7",   
  "protein_id": "WP_002356636.1",
  "ref_organism": "Enterococcus faecalis",
  "organism_detail": "strain ATCC 700802/V583",        
  "accession": "AAO82218",
  "ref_seq": "MNRKEKTNLDSRIDYGVILPVFLLSLIGMLSLYVALYNDPSKPKIGSLLMKQGLWYLVGGLSIVIIMHFSSKLLWRLTPVFYALGLVLMGLLLKFYDPVLAEQTGSKNWIRFGGTTFQPSELMKIAFILMLAYIVTMHNVKYVDRTLKSDFWLIAKMLLVAIPVIVLVLLQKDFGTMLVFLAIFGGVFLMSGITWKIIVPVFILAALVGAGTIYLITTETGRDLLSKLGVEAYKFDRIDLWLNPFHTDPDRSFQPALALTAIGSGGLFGKGFNVSDVYVPVRESDMIFTVVGENFGFIGGCFIILLYFILIYRMIRVCFDTNNEFYAYIATGIIMMILFHVFENIGANIGLLPLTGIPLPFISQGGSSILGNMIGVGLIMSMRYQQETVRTRSGR",
  "article_based": True
}

MurG = {
  "protein": "MurG",
  "gene": ["murG"],
  "EC": ["2.4.1.227"],
  "alt": ["MurG",
          "UDP-N-acetylmuramate-alanine ligase",
          "UDP-N-acetylglucosamine--N-acetylmuramyl-(pentapeptide) pyrophosphoryl-undecaprenol N-acetylglucosamine transferase",
          "Undecaprenyl-PP-MurNAc-pentapeptide-UDPGlcNAc GlcNAc transferase U"],
  "OrthoDB": "-",
  "eggNOG": "COG0707",
  "Pfam": ["PF04101", "PF03033"],
  "UniProt": "O07109",
  "protein_id": "WP_002379204.1",
  "ref_organism": "Enterococcus faecalis",
  "organism_detail": "strain ATCC 700802/V583",  
  "accession": "AAO80800",
  "ref_seq": "MKILVTGGGTGGHIYPALSFVEHVKKEAPATEFLYVGTENGLESQIVPKAKIPFKTIKIQGFKRSLSPQNFKTIYLFLTSINKAKKIIREFQPDVVIGTGGYVSGAVVYAAHQLKIPTIIHEQNSIPGMTNKFLSRYVDKIAICFPDVASFFPKEKTILTGNPRGQEVVTVEKSAILSEFGLDPAKKTVVLFGGSRGALKINQAFEQAFPLFEEREYQVLYASGERYYQELQESLKFSEKKLTNISVQPYIDKMVEVMANTDLMVGRAGATSIAEFTALGLPAILIPSPYVTNDHQTKNAQSLVKVGAVEMIPDAELTGARLVAAIDDILLNNEKRQQMATASKGEGIPDASDRLYQVVKTLV",
  "article_based": True
}

MurC = {
  "protein": "MurC",
  "gene": ["murC"],
  "EC": ["6.3.2.8"],
  "alt": ["MurC", "UDP-N-acetylmuramate--L-alanine ligase",
          "UDP-N-acetylmuramoyl-L-alanine synthetase"],
  "OrthoDB": "-",
  "eggNOG": "COG0773",
  "Pfam": ["PF01225", "PF02875", "PF08245"],
  "UniProt": "Q833N6",
  "protein_id": "WP_002357163.1",
  "ref_organism": "Enterococcus faecalis",
  "organism_detail": "strain ATCC 700802/V583",  
  "accession": "AAO81660",
  "ref_seq": "MGNQENKLYHFVGIKGSGMSSLALVLHQKGYNVQGSDVEEYFFTQRDLEKSGVPILPFNADNIDKDMIVIAGNAFPDTHEEIARAIELGAEVIRYHDFIARFIEPYTSIAVTGSHGKTSTTGLLAHVLSGINPTSYLIGDGTGHGEPDADFFAFEACEYRRHFLAYSPDYAIMTNIDFDHPDYYKSIEDVFSAFQTMAHQVKKGIFAYGDDKYLRQLESEVPVYYYGVSEEDDIQARNIQRTTEGSSFDVYHKDDFVGHFVLPAFGHHNIMNALGVIAVAYFEKLDMQKVAEEMLSFKGVKRRFSEKKVSDMIIVDDYAHHPAEIKATIDGARQKYPDKEIIAVFQPHTFTRTIALMDEFAEALDLADEVFLCNIFGSARETQGEVRIEDLGEKIQKGGQVITEDNVSPLLDFENAVVVFMGAGDVQKFEQAYETLLSNTTRNVL",
  "article_based": True
}

MurB = {
  "protein": "MurB",
  "gene": ["murB", "yijB"],
  "EC": ["1.3.1.98"],
  "alt": ["MurB", "YijB"
          "UDP-N-acetylmuramate dehydrogenase", 
          "UDP-N-acetylenolpyruvoylglucosamine reductase"],
  "OrthoDB": "-",
  "eggNOG": "COG0812",
  "Pfam": ["PF01565", "PF02873"],
  "UniProt": "Q830P3",
  "protein_id": "WP_002356404.1",
  "ref_organism": "Enterococcus faecalis",
  "organism_detail": "strain ATCC 700802/V583",   
  "accession": "AAO82434",
  "ref_seq": "MNTKAMLETLNEITLLVDEPLKNVTFTKTGGPADVLALPKTKKEVEEIVAYCREQGLSWLVLGNASNLIVRDGGIRDVVIMLTEMKEIKVAGTTMIVDAGAKLIDTTYEALAADLTGFEFACGIPGSVGGAVYMNAGAYGGEIKDVFQSAEVLLADGTIQTMTKEDLNFRYRHSEIQELHCIVLQATFALEKGNHAEIKAQMDELTELRELKQPLEYPSCGSVFKRPVGHFTGKLIQDAGLQGLKWGGAQISEKHAGFIVNIDHATATDYVELIAHIQEVIKEKFDVELQTEVRIIGEEV",
  "article_based": True
}

MurA = {
  "protein": "MurA",
  "gene": ["murA", "murZ"],
  "EC": ["2.5.1.7"],
  "alt": ["MurA", "MurZ"
          "UDP-N-acetylglucosamine 1-carboxyvinyltransferase", 
          "UDP-N-acetylglucosamine enolpyruvyl transferase"],
  "OrthoDB": "-",
  "eggNOG": "COG0766",
  "Pfam": ["PF00275"],
  "UniProt": "Q831A8",          
  "protein_id": "WP_002356562.1",
  "ref_organism": "Enterococcus faecalis",
  "organism_detail": "strain ATCC 700802/V583", 
  "accession": "AAO80969",
  "ref_seq": "MEQIIVHGGNTKLEGTVKIEGAKNAVLPILAATLLAEEGVTTLKNVPILSDVFTMNQVIKHLNVAIDFDEDANEVTIDATQPLGIEANYEYVSKMRASIVVMGPLLARNGHAKVAMPGGCAIGKRPIDLHLKGFQALGAKIIQKNGYIEAIADELIGNTIYLDFPSVGATQNIMMAAVRAKGTTIIENVAREPEIVDLANILNKMGANVIGAGTETMRIEGVDKLHAVEHSIVQDRIEAGTFMVAAAMTEGNVLIEEAISEHNRPLISKLTEMGAIIEEEENGIRVIGPKHLKPTDVKTMPHPGFPTDMQAQMTAIQMFAEGTSIVTETVFENRYQHLEEMRRMNADLKIDGNIAVINGGNELQGAAVEATDLRAAAALILVGLRANGITRVSNLKYLDRGYYEFHKKLQKLGANVERVNDEKIEEKQATTVI",
  "article_based": True
}

DdlB = {
  "protein": "DdlB",
  "gene": ["ddlB", "ddl"],
  "EC": ["6.3.2.4"],
  "alt": ["DdlB" "Ddl", 
          "D-alanine—D-alanine ligases B"],
  "OrthoDB": "-",
  "eggNOG": "COG1181",
  "Pfam": ["PF07478", "PF01820"],
  "UniProt": "Q47758",  
  "protein_id": "WP_010774177.1",
  "ref_organism": "Enterococcus faecalis",
  "organism_detail": "strain ATCC 700802/V583",      
  "accession": "AAO80655",
  "ref_seq": "MKIILLYGGRSEEHDVSVLSAYSVLNAIYYKYYQVQLVFISKDGQWVKGPLLSERPQNKEVLHLTWAQTPEETGEFSGKRISPSEIYEEEAIVFPVLHGPNGEDGTIQGFMETINMPYVGAGVLASANAMDKIMTKYLLQTVGIPQVPFVPVLRSDWKGNPKEVFEKCEGSLIYPVFVKPANMGSSVGISKVENREELQEALEEAFRYDARAIVEQGIEAREIEVAILGNEDVRTTLPGEVVKDVAFYDYDAKYINNTIEMQIPAHVPEEVAHQAQEYAKKAYIMLDGSGLSRCDFFLTSKNELFLNELNTMPGFTDFSMYPLLWENMGLKYSDLIEELIQLALNRFK",
  "article_based": True
}

FtsQ = {
  "protein": "FtsQ",
  "gene": ["ftsQ", "divIB"],
  "EC": ["-"],
  "alt": ["FtsQ", "DivIB",
          "cell division protein FtsQ",
          "cell division protein DivIB"],
  "OrthoDB": "-",
  "eggNOG": "COG1589",
  "Pfam": ["PF03799", "PF08478"],
  "UniProt": "Q836V6",          
  "protein_id": "WP_002368241.1",
  "ref_organism": "Enterococcus faecalis",
  "organism_detail": "strain ATCC 700802/V583",  
  "accession": "AAA22393",
  "ref_seq": "MWKISNENDIFKKRKPLPPKKSEESQPELTPWQKQNQEYLKKQAEEAASKGENEQAEVTITLQEQSQEEPQQHLPQETVEEEEHFADRLPNVKKTRNKRLYRRLAFILTCLGTAILVALYFVSPLSRLSEVTVSGNKSVESQAIIQQSKLETGSGLWEQYSNRNYFSANIQKKFPIIKKANIKLNGINSFKIDIQEYQIVALAATKGGYHPILENGKTLAETTKAAESGKPIFENFKEDKLIPELMASYNKLPQEIKQGISEIKYAPSKTNKDLINVYMNDGNRVIVNISDLSEKMAYYSQVAEQMDKPGIVDMEVGIFSYPYEKESEETGSEVSEDSAVENQEVVDPNAGVATDEANNGTPTNGENQEVQQAE",
  "article_based": False
}

FtsA = {
  "protein": "FtsA",
  "gene": ["ftsA", "divA"],
  "EC": ["-"],
  "alt": ["FtsA", "DivA", 
          "cell division protein FtsA"],
  "OrthoDB": "-",
  "eggNOG": "COG0849",
  "Pfam": ["PF14450", "PF02491", "PF11983"],
  "UniProt": "O07111",          
  "protein_id": "WP_002355898.1",
  "ref_organism": "Enterococcus faecalis",
  "organism_detail": "strain ATCC 700802/V583",  
  "accession": "AAO80802",
  "ref_seq": "MAKTGMYVGLDIGTTSVKVVVAEYIEGQMNIIGVGNAKSDGLNRGIVVDIDQTVQAIQRAVRQAEEKAGIQIKSVNVGLPANLLEVESCQGMIAVSSESKEITDEDVRNVASAALVRSTPPERQIVAILPQDFTVDGFEGIKDPRGMLGVRMEMFGVVYTGPKTIIHNIRKCVEKAGLGINELVITPLALTETILTDGEKDFGTIVIDMGGGQTTTSVIHDKQLKFTHVNQEGGEFITKDISIVLNTSFNNAEALKINYGDAYPERTSANEEFPVDVIGKSEPVRVDERYLSEIIEARVEQILRKSKEVLDEIDAFELPGGVVLTGGAASMPGIVDLAQEIFEANVKLYVPNHMGLRNPVFANVISIVEYSAQLNDIYHIAKYAIPGEKSKPAQSVAVQQEVRYDTYAEQPQEEYEEFNERESGEKVTGKIKDFFSNIFD",
  "article_based": True
}

FtsZ = {
  "protein": "FtsZ",
  "gene": ["ftsZ", "sfiB"],
  "EC": ["-"],
  "alt": ["FtsZ", "SfiB", 
          "cell division protein FtsZ"],
  "OrthoDB": "-",
  "eggNOG": "COG0206",
  "Pfam": ["PF12327", "PF00091"],
  "UniProt": "O08439",    
  "protein_id": "WP_002355899.1",
  "ref_organism": "Enterococcus faecalis",
  "organism_detail": "strain ATCC 700802/V583",         
  "accession": "AAO80803",
  "ref_seq": "MEFSLDNNINNGAVIKVIGVGGGGGNAVNRMIEENVKGVEFITANTDVQALKHSKAETVIQLGPKYTRGLGAGSQPEVGQKAAEESEQVISESLQGADMIFITAGMGGGTGTGAAPVVAKIAKELGALTVGVVTRPFSFEGPKRGRFAAEGIALLKENVDTLLIISNNRLLEVVDKKTPMLEAFREADNVLRQGVQGISDLITAPGYVNLDFADVKTVMENQGTALMGIGVASGEERVIEATKKAISSPLLETSIDGAEQVLLNITGGLDMTLFEAQDASDIVTNAASGDVNIILGTSINEDLGDEIRVTVIATGIDESKKDRKPHRQTRQAVQPMQQTTQSVEMDQPKSQEEASAFGDWDIRREQNTRPKVDESSLEQVDKKEFDTFHREEPNHNDDELSTPPFFRRKR",
  "article_based": True
}

target_list = [
  MraZ, MraW, FtsL, FtsI, MurE, MurF, MraY, MurD, FtsW, 
  MurG, MurC, MurB, MurA, DdlB, FtsQ, FtsA, FtsZ
]

target_color = {
    "MraZ": "#8ED3C7",
    "MraW": "#F99FB5",
    "FtsL": "#2A9D8F",
    "FtsI": "#BEBADB",
    "MurE": "#FB7F72",
    "MurF": "#81B1D3",
    "MraY": "#FDB364",
    "MurD": "#B2DE68",
    "FtsW": "#E4B7CD",
    "MurG": "#B6C8FE",
    "MurC": "#BD7FBB",
    "MurB": "#CDEBC3",
    "MurA": "#DFC27C",
    "DdlB": "#C7E8FA",
    "FtsQ": "#A95C68",
    "FtsA": "#FCBBA2",
    "FtsZ": "#F7DA84",
    "blank": "#F0F0F0",
    "etc": "#C0C0C0"
}